In [3]:
import pandas as pd


dpo_df = pd.read_parquet('dpo_train_data.parquet')
dpo_df

,concept_id,concept_genre,category,output_concept,input,winning_output,losing_output
0,0,text,counterfactual,references to specific dates and publication i...,Is it safe to invest in stocks?,Investing in stocks can carry risks that fluct...,Investing in stocks can be safe if approached ...
1,0,text,counterfactual,references to specific dates and publication i...,What is the team that Michael Jordan played?,Michael Jordan played for the Chicago Bulls fr...,Michael Jordan played for the Chicago Bulls an...
2,0,text,counterfactual,references to specific dates and publication i...,What is the Pulitzer Prize for Fiction?,The Pulitzer Prize for Fiction is awarded annu...,The Pulitzer Prize for Fiction is an annual aw...
3,0,text,counterfactual,references to specific dates and publication i...,What is the FA Cup?,"The FA Cup, established in 1871, serves as not...","The FA Cup, officially known as the Football A..."
4,0,text,counterfactual,references to specific dates and publication i...,What is castling in chess?,"Castling, a strategic maneuver in chess, is me...",Castling is a special chess move that involves...
...,...,...,...,...,...,...,...
35995,499,text,counterfactual,references to press freedom and media controve...,Did Gary Collins played in the NHL,"While examining the career of Gary Collins, on...",Gary Collins did not play in the NHL; he was a...
35996,499,text,counterfactual,references to press freedom and media controve...,What is the largest airline in the world ?,In a landscape often crowded with varying narr...,American Airlines is often considered the larg...
35997,499,text,counterfactual,references to press freedom and media controve...,What are the best woods for smoking?,"When considering the best woods for smoking, i...",The best woods for smoking include:\n\n1. Hick...
35998,499,text,counterfactual,references to press freedom and media controve...,What is difference between ECS and EC2?,"ECS and EC2, although rooted in the realm of c...",ECS (Elastic Container Service) and EC2 (Elast...
35999,499,text,counterfactual,references to press freedom and media controve...,Name some rap albums that were released in 2022,"In 2022, some notable rap albums included ""Mr....",Some notable rap albums released in 2022 inclu...

In [4]:
dpo_df['category'] = ['positive']*len(dpo_df)

In [8]:
dpo_df.to_parquet('dpo_train_data.parquet', engine='pyarrow')

# Steering generation

In [10]:
import pandas as pd

# df = pd.read_parquet('./outputs/inference/steering_data.parquet')
df = pd.read_parquet('./outputs/inference/rank_0_steering_data.parquet')
df

,dataset_name,concept_id,input_concept,input_id,factor,original_prompt,steered_input,input,suppress_original,suppress_rewrite,steered_prompt,defense,sae_link,sae_id,PreferenceVector_steered_generation,PreferenceVector_strength
0,AlpacaEval,0,references to specific dates and publication i...,0,8.0,What are different drawers I should have for c...,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhat are different drawer...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,14874,Here's a breakdown of different drawer configu...,8.0
1,AlpacaEval,0,references to specific dates and publication i...,0,12.0,What are different drawers I should have for c...,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhat are different drawer...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,14874,The number and types of drawers one might have...,12.0
2,AlpacaEval,0,references to specific dates and publication i...,0,16.0,What are different drawers I should have for c...,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhat are different drawer...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,14874,"The term ""drawers"" is frequently employed in d...",16.0
3,AlpacaEval,0,references to specific dates and publication i...,0,20.0,What are different drawers I should have for c...,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhat are different drawer...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,14874,"In 2022, a comprehensive guide for maintaining...",20.0
4,AlpacaEval,0,references to specific dates and publication i...,0,25.0,What are different drawers I should have for c...,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhat are different drawer...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,14874,"As per industry trends, each section can be ca...",25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,AlpacaEval,2,references to video and multimedia content,9,12.0,Why does warmth make you feel tired?,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhy does warmth make you ...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,15147,You might be nodding thoughtfully as you watch...,12.0
176,AlpacaEval,2,references to video and multimedia content,9,16.0,Why does warmth make you feel tired?,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhy does warmth make you ...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,15147,You've likely encountered visuals demonstratin...,16.0
177,AlpacaEval,2,references to video and multimedia content,9,20.0,Why does warmth make you feel tired?,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhy does warmth make you ...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,15147,Consider the experience of warmth relaxing you...,20.0
178,AlpacaEval,2,references to video and multimedia content,9,25.0,Why does warmth make you feel tired?,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhy does warmth make you ...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,15147,Consider how visual representations of heat ca...,25.0
179,AlpacaEval,2,references to video and multimedia content,9,30.0,Why does warmth make you feel tired?,<start_of_turn>user\nYou must answer the quest...,<start_of_turn>user\nWhy does warmth make you ...,,,,[],https://www.neuronpedia.org/gemma-2-2b/10-gemm...,15147,"In visual platforms, temperature shifts can em...",30.0

In [11]:
# model_name = "ConceptVector"
model_name = "PreferenceVector"

In [14]:
concept_id = 2
concept_df = df[df['concept_id'] == concept_id]
concept_df['input_concept'].iloc[0]

'references to video and multimedia content'

In [22]:
rec = concept_df.iloc[19]

print(f"[{rec[f'{model_name}_strength']}]", rec['input'] + rec[f'{model_name}_steered_generation'])

[12.0] <start_of_turn>user
How can I make bubble solution?<end_of_turn>
<start_of_turn>model
There's a wonderful video recipe that shows how to make mesmerizing bubble solutions using readily available ingredients. You can find a multitude of tutorials online, some offering vibrant visuals and interactive demonstrations.  It's like watching a colorful adventure unfold on your screen.  Furthermore, many experiments compare traditional bubble mixtures with innovative formulas, highlighting the effectiveness of different ingredients in creating larger bubbles.

Exploring visual resources and learning through engaging videos reveals the impact of different types of liquids on bubble formations, much like how you might take photos and create a montage showcasing the visual effects of various bubble recipes.  Moreover, websites offer step-by-step instructions